apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: argocd
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file for new project </h1> <br>
    <h2> <color green>It is ferst exepted test </h2> 
    
    </html>
